server:
  port: 8777
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mysql://localhost:3306/authdb?useSSL=false
    username: root
    password: 98633589
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  # App Properties
Cvioo:
  app:
    jwtSecret: CviooSecretKey
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000