server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/docdb?useSSL=false
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER



